config/routes.rb
Rails.application.routes.draw do
  root to: 'search#index'
  resources :artists
  get '/search', to: 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  paginates_per 10

  has_and_belongs_to_many :locations
  has_and_belongs_to_many :tags

  def self.search(query)
    return Artist.all if query.blank?

    artist_ids = []
    tags = query.split(' ')
    matched_tags = []

    tags.each do |tag_name|
      matched_tags += Tag.where('names @> ?', { name_en: tag_name }.to_json).map(&:id)
    end

    Artist.includes(:tags).where(tags: { id: matched_tags })
  end
end

app/models/artists_location.rb
class ArtistsLocation < ApplicationRecord
  belongs_to :artist
  belongs_to :location
end

app/models/artists_tag.rb
class ArtistsTag < ApplicationRecord
  belongs_to :artist
  belongs_to :tag
end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :artists

  def name
    names['name_en']
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :artists

  def name
    names['name_en']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist_description = @artist.descriptions['description_en']

    @artist_location = 'Not specified'
    if @artist.locations.any?
      @artist_location = @artist.locations.first.names['name_en']
    end
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @tags = Tag.all
    @locations = Location.all
  end

  # GET /artists/1/edit
  def edit
    @tags = Tag.all
    @locations = Location.all
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new
    use_some_form_object_to_do_this_instead(@artist)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    @artist.tags.clear
    @artist.locations.clear
    use_some_form_object_to_do_this_instead(@artist)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :tags, :locations, :description_en, :description_de)
    end

    def use_some_form_object_to_do_this_instead(record)
      record.name = artist_params[:name]
      record.descriptions = {}
      record.descriptions['description_en'] = artist_params['description_en']
      record.descriptions['description_de'] = artist_params['description_de']
      record.tags << Tag.where(id: params[:artist][:tags])
      record.locations << Location.where(id: params[:artist][:locations])
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # GET /search
  def index
    @artists = Artist.search(params[:query])
    @artists = @artists.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="field">
    <%= form.label :description_en %>
    <%= form.text_field :description_en, id: :artist_description_en %>
  </div>

  <div class="field">
    <%= form.label :description_de %>
    <%= form.text_field :description_de, id: :artist_description_de %>
  </div>

  <%= collection_select(:artist, :tags, @tags, :id, :name,{:include_blank => 'None'}, {:multiple => true, :name=>'artist[tags][]',:selected => 0}) %>

  <%= collection_select(:artist, :locations, @locations, :id, :name,{:include_blank => 'None'}, {:multiple => true, :name=>'artist[locations][]',:selected => 0}) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manage Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>


<%= link_to "Or search them here", search_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artist_description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @artist_location %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtistsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Artists by tag</h1>

<%= form_tag search_path, method: 'get' do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end -%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= link_to 'Show', artist %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @artists %>


<%= link_to "Or manage them here", artists_path %>